trigger: none
# - main

pool:
  vmImage: ubuntu-latest

variables:
  acr_name: nagclkcontainerregistry-h5hxg6cub6cgb2b9
  tag: 1.0.0-$(Build.BuildId)
  

steps:

- task: AzureCLI@2
  displayName: Docker Build & Push
  inputs:
    azureSubscription: 'Nag-Azure-Connect'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t $(acr_name).azurecr.io/webapp:$(tag) app-dotnet
      az acr login -n $(acr_name)
      docker push $(acr_name).azurecr.io/webapp:$(tag)
      
- task: replacetokens@6
  displayName: 'Replace Image TAG'
  inputs:
    rootDirectory: '02_sample_app_yaml'
    targetFiles: 'app-deploy.yaml'
    encoding: 'auto'
    addBOM: true
    actionOnMissing: 'warn'
    tokenPrefix: '__'
    tokenSuffix: '__'
    recursive: true
    transforms: true
    telemetryOptout: true
   
- task: replacetokens@6
  inputs:
    root: '02_sample_app_yaml'
    sources: '02_sample_app_yaml/app-deploy.yaml'
    addBOM: true
    recursive: true
    transforms: true
    telemetryOptout: true


- script: cat 02_sample_app_yaml/app-deploy.yaml
  displayName: View app-deploy.yaml

- task: Kubernetes@1
  displayName: Kubernetes Deploy
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Nag-Azure-Connect'
    azureResourceGroup: 'myResourceGroup'
    kubernetesCluster: 'MY_AKS_CLUSTER_NAME'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '02_sample_app_yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
